### ISSUE TITLE
tried to follow jupyter install - but getting 404 error calling pivot_ui(df) on my dataframe

### ISSUE THREAD

**Issue by gpillemer** [nicolaskruchten/jupyter_pivottablejs#6] opened 2015-10-16 18:52 UTC
tried to follow jupyter install - (pip install pivottablejs) but getting 404 error calling pivot_ui(df) on my dataframe

**Comment by gpillemer** [comment] 2015-10-16 19:38
Oh ok - so i see the html file that is written in the directory - opening that generates the pivot. But where does the html need to be saved to open in a new cell in the jupyter browser?

**Comment by mbatchkarov** [comment] 2015-11-12 17:22
This is a duplicate of #5 .

**Comment by gpillemer** [comment] 2015-11-12 18:09
calling the pivot_ui(df) spits out a file called pivottablejs.html by
default.
the 404 error is arising because it cannot find that file.
make sure that the current directory of the notebook is the same directory
as the file that is outputted and you should be good!
its an awesome tool!

**Comment by nicolaskruchten** [comment] 2015-11-12 19:02
I'm sure there is a simple fix here to ensure that the file is always outputted in the right place to be rendered, but I can't replicate this problem locally. Can I get a sense of what your Jupyter settings are/where you are launching Jupyter and/or this code from to get this error?

**Comment by gpillemer** [comment] 2015-11-12 19:30
In my case, i have my set up my notebook config settings to change my
current directory upon launching the notebook so that it is in the path of
particular modules.
Hence, when i first tried to output the pivot_ui - it saved the html in the
current directory, but my notebook was in another.

Thanks again for an awesome tool - it has really helped me a lot.

G

**Comment by nicolaskruchten** [comment] 2017-05-07 16:42
You can just provide an absolute path for `outfile_path`, no?

**Comment by nicolaskruchten** [comment] 2017-05-08 01:05
To reply to my own question: no, this is insufficient. Reopening.

**Comment by nicolaskruchten** [comment] 2017-05-08 03:04
This is now addressed via the `url_prefix` parameter.

**Closed by nicolaskruchten** 2017-05-08 03:04 UTC

**Comment by kutea18** [comment] 2018-05-16 10:33
Don't get how to do it
